---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

transport_data <- read_csv("data/clean_data/hierarchical_data.csv") %>% 
  filter(str_detect(id, "^Transport"))
```

```{r}
transport_emissions <- transport_data %>% 
  filter(!value < 0)
```

```{r}
transport_emissions %>% 
  filter(year == 2018) %>% 
  group_by(id, label, parent) %>% 
  summarise(value = sum(value, na.rm = TRUE), .groups = 'drop_last')
```

```{r}
transport_emissions %>% 
  filter(year == 2018) %>% 
  group_by(id, label, parent) %>% 
  summarise(value = sum(value, na.rm = TRUE), .groups = 'drop_last') %>%
  mutate(units = "megatonnes of CO2 equivelant") %>% 
  data.frame(stringsAsFactors = FALSE) %>% 
  plot_ly(
    ids = ~id,
    labels = ~label,
    parents = ~parent,
    values = ~value,
    type = "treemap",
    branchvalues = "total",
    maxdepth = 3,
    text =  ~units,
    textinfo = 'label+percent root+value+text'
  )
```

```{r}
get_sector_percentages_emissions <- function(all_emissions, sector, emission_year) {
  all_emissions %>% 
    filter(!value < 0) %>% 
    filter(year == emission_year) %>%
    group_by(ccp_mapping) %>% 
    summarise(value = sum(value, na.rm = TRUE), .groups = 'drop_last') %>% 
    summarise(ccp_mapping, p = value/sum(value)) %>%
    filter(ccp_mapping == sector) %>% 
    pull(p)
}
```

```{r}
transport_p <- get_sector_percentages_emissions(emissions_data,
                       sector = "Transport",
                       emission_year = 2018)

transport_p
```

```{r}
new_ulevs <- read_csv(
  "data/clean_data/transport/newly_registered_vehicles_and_ulevs.csv"
  )
```

```{r}
new_ulevs %>% 
  distinct(body_type)
```


```{r}
new_ulevs %>% 
  mutate(vehicle_type = str_to_title(str_replace_all(vehicle_type, "_", " "))) %>% 
  rename(body_type = vehicle_type) %>% 
  write_csv("data/clean_data/transport/newly_registered_vehicles_and_ulevs.csv")
```


```{r}
library(tidyverse)
```


```{r}
new_ulevs %>% 
  mutate(p_new_ulevs = n_ulevs_registered/n_registered) %>%
  pivot_longer(cols = c(n_registered, n_ulevs_registered, p_new_ulevs), names_to = "statistic", values_to = "value") %>% 
  mutate(statistic = recode(statistic,
    "n_registered" = "Vehicle Registrations",
    "n_ulevs_registered" = "ULE Vehicle Registrations",
    "Proportion of New Vehicle Registrations that are ULEV (%%)" = "Proportion of New Vehicle Registrations that are ULEV"
  )) %>% 
  mutate(units = statistic) %>% 
  write_csv("data/clean_data/transport/newly_registered_vehicles_and_ulevs.csv")
  filter(statistic == "Proportion of New Vehicle Registrations that are ULEV") %>% 
  ggplot() +
  aes(x = year, y = value) +
  geom_line() +
  facet_wrap(~body_type)
```

